/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.ui.contentassist;

import org.itea2.amalthea.variability.dependency.ui.contentassist.AbstractDependencyProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DependencyProposalProvider extends AbstractDependencyProposalProvider {
}
