/*
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.itea2.amalthea.variability.dependency.services.DependencyGrammarAccess;

@SuppressWarnings("all")
public class DependencySyntacticSequencer extends AbstractSyntacticSequencer {

	protected DependencyGrammarAccess grammarAccess;
	protected AbstractElementAlias match_HierarchicalDependency_ExclusiveKeyword_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DependencyGrammarAccess) access;
		match_HierarchicalDependency_ExclusiveKeyword_1_q = new TokenAlias(false, true, grammarAccess.getHierarchicalDependencyAccess().getExclusiveKeyword_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_HierarchicalDependency_ExclusiveKeyword_1_q.equals(syntax))
				emit_HierarchicalDependency_ExclusiveKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '(Exclusive)'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '[HierarchicalDependency]' (ambiguity) systemPart=SystemPart
	 */
	protected void emit_HierarchicalDependency_ExclusiveKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
