/*
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDependencyScopeProvider extends DelegatingScopeProvider {
}
