<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ample" nsURI="http://itea.amalthea.org/variability/0.7.0/ample"
    nsPrefix="ample">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="*&#xA;*******************************************************************************&#xA; Copyright (c) 2017 Dortmund University of Applied Sciences and Arts, Paderborn University and others.&#xA; All rights reserved. This program and the accompanying materials&#xA; are made available under the terms of the Eclipse Public License v1.0&#xA; which accompanies this distribution, and is available at&#xA; http://www.eclipse.org/legal/epl-v10.html&#xA;*******************************************************************************"/>
    <details key="basePackage" value="org.itea2.amalthea.variability"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelName" value="Ample"/>
    <details key="prefix" value="Ample"/>
    <details key="editDirectory" value="/org.itea2.amalthea.variability.ample.edit/src-gen"/>
    <details key="forceOverwrite" value="true"/>
    <details key="creationSubmenus" value="true"/>
    <details key="generateSchema" value="true"/>
    <details key="loadInitialization" value="false"/>
    <details key="copyrightText" value="*******************************************************************************&#xD;&#xA; Copyright (c) 2017 Dortmund University of Applied Sciences and Arts, Paderborn University and others.&#xD;&#xA; All rights reserved. This program and the accompanying materials&#xD;&#xA; are made available under the terms of the Eclipse Public License v1.0&#xD;&#xA; which accompanies this distribution, and is available at&#xD;&#xA; http://www.eclipse.org/legal/epl-v10.html&#xD;&#xA;&#xD;&#xA;    Generated using Eclipse EMF&#xD;&#xA;&#xD;&#xA;*******************************************************************************"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemFamily">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class aggregates different system parts (e.g. software, hardware, os)&#xA;and function as root element for the variability modeling process"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureModels" upperBound="-1"
        eType="#//FeatureModel" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardwareVariabilityModels"
        upperBound="-1" eType="#//HardwareVariabilityModel" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*************************************************************************************&#xA;*************************** Feature Model ******************************************&#xA;************************************************************************************"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scope" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//Mandatory"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//FeatureConstraint" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productConfigurations"
        upperBound="-1" eType="#//ProductConfiguration" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureTypes" upperBound="-1"
        eType="#//FeatureType" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductConfiguration">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class represents a distinct product configuration where all variation points of a Feature Model are bound"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedFeatures" upperBound="-1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstraint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class realizes cross-tree constraints between specific features by means of require and exclude"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//ConstraintType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a distinct product feature"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" eType="#//FeatureType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solitaryFeatures" upperBound="-1"
        eType="#//SolitaryFeature" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureGroups" upperBound="-1"
        eType="#//FeatureGroup" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes the scope of a feature in order to support references through dependencies."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class make use of a xtext grammar to describe a cross-dependency, i.e. a depedency between elements of different system parts"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SolitaryFeature" abstract="true" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mandatory" eSuperTypes="#//SolitaryFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Features of this category are mandatory for the product configuration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional" eSuperTypes="#//SolitaryFeature">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Features of this category are optional for the product configuration"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureGroup" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeGroup" eSuperTypes="#//FeatureGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="XOR decision for a given set of group features"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeFeatures" lowerBound="2"
        upperBound="-1" eType="#//Alternative" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrGroup" eSuperTypes="#//FeatureGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="By default, at least one feature of an or group have to be selected. Can be refined with a cardinality (e.g. 2 out of 5 features have to be selected)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orFeatures" lowerBound="2"
        upperBound="-1" eType="#//Or" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupFeature" abstract="true" eSuperTypes="#//Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="#//GroupFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//GroupFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareVariabilityModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*************************************************************************************&#xA;*********************** Hardware Variability Model *********************************&#xA;************************************************************************************"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecus" lowerBound="1" upperBound="-1"
        eType="#//ECU" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hwConfigs" upperBound="-1"
        eType="#//HardwareConfiguration" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationPoints" upperBound="-1"
        eType="#//HVM_VariationPoint" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vpConstraints" upperBound="-1"
        eType="#//HVM_VariationPointConstraint" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedVPs" upperBound="-1"
        eType="#//HVM_VariationPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HardwareElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customProperty" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericComponents" upperBound="-1"
        eType="#//GenericComponent" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pins" upperBound="-1" eType="#//Pin"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECU" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buses" upperBound="-1"
        eType="#//Bus" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" eType="#//Dimension"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="microcontrollers" lowerBound="1"
        upperBound="-1" eType="#//Microcontroller" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="peripherals" upperBound="-1"
        eType="#//Peripheral" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Microcontroller" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedMCs" upperBound="-1"
        eType="#//Microcontroller"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cores" lowerBound="1" upperBound="-1"
        eType="#//Core" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedMemory" upperBound="-1"
        eType="#//Memory" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Core" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitWidth" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isa" unique="false" eType="#//ISA_Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" eType="#//Frequency"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="caches" lowerBound="1"
        upperBound="-1" eType="#//Cache" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Memory" abstract="true" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//DataSize"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cache" eSuperTypes="#//Memory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//CacheType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" eType="#//Frequency"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RAM" eSuperTypes="#//Memory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVolatile" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequency" eType="#//Frequency"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROM" eSuperTypes="#//Memory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="romType" unique="false"
        eType="#//ROM_Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readTime" eType="#//DataRate"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="writeTime" eType="#//DataRate"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//BusType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSerial" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rwType" unique="false"
        eType="#//RW_Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataRate" eType="#//DataRate"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Peripheral" abstract="true" eSuperTypes="#//HardwareElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//Peripheral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actuator" eSuperTypes="#//Peripheral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Watchdog" eSuperTypes="#//Peripheral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="standard" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericComponent" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hwType" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//Unit" containment="true"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//HardwareElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedPins" upperBound="-1"
        eType="#//Pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HVM_VariationPoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" Variability"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variationElements" upperBound="-1"
        eType="#//VariationElement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedElement" lowerBound="1"
        eType="#//HardwareElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeElements" upperBound="-1"
        eType="#//HardwareElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="addElements" upperBound="-1"
        eType="#//HardwareElement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="replaceElement" eType="#//HardwareElement"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HVM_VariationPointConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintType" unique="false"
        eType="#//ConstraintType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//HVM_VariationPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//HVM_VariationPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" Attributes"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numValue" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EDoubleObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" unique="false" eType="#//LengthUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frequency" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequencyUnit" unique="false"
        eType="#//FrequencyUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataRate" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataRateUnit" unique="false"
        eType="#//DataRateUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSize" eSuperTypes="#//Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSizeUnit" unique="false"
        eType="#//DataSizeUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="*************************************************************************************&#xA;**********************************Enumerations**************************************&#xA;************************************************************************************"/>
    </eAnnotations>
    <eLiterals name="_undefined_" literal="&lt;Undefined>"/>
    <eLiterals name="require" literal="Require"/>
    <eLiterals name="exclude" literal="Exclude"/>
    <eLiterals name="impedes" literal="Impedes"/>
    <eLiterals name="suggests" literal="Suggests"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FrequencyUnit">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="hz" literal="Hz"/>
    <eLiterals name="khz" literal="KHz"/>
    <eLiterals name="mhz" literal="MHz"/>
    <eLiterals name="ghz" literal="GHz"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataRateUnit">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="bitpers" literal="BitPerS"/>
    <eLiterals name="kibitpers" literal="KibiBitPerS"/>
    <eLiterals name="mebibitpers" literal="MebiBitPerS"/>
    <eLiterals name="gibitpers" literal="GibiBittPerS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataSizeUnit">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="byte" literal="Byte"/>
    <eLiterals name="kibibyte" literal="KibiByte"/>
    <eLiterals name="mebibyte" literal="MebiByte"/>
    <eLiterals name="gibibyte" literal="GibiByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ISA_Type">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="risc" literal="RISC"/>
    <eLiterals name="cisc" literal="CISC"/>
    <eLiterals name="vliw" literal="VLIW"/>
    <eLiterals name="simd" literal="SIMD"/>
    <eLiterals name="other" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BusType">
    <eLiterals name="_undefined_" literal="UNDEFINED"/>
    <eLiterals name="can" literal="CAN"/>
    <eLiterals name="ethernet" literal="ETHERNET"/>
    <eLiterals name="lin" literal="LIN"/>
    <eLiterals name="flexray" literal="FLEXRAY"/>
    <eLiterals name="spi" literal="SPI"/>
    <eLiterals name="ttcan" literal="TTCAN"/>
    <eLiterals name="other" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RW_Type">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="R" literal="R"/>
    <eLiterals name="W" literal="W"/>
    <eLiterals name="RW" literal="RW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ROM_Type">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="eprom" literal="EPROM"/>
    <eLiterals name="eeprom" literal="EEPROM"/>
    <eLiterals name="flash" literal="FLASH"/>
    <eLiterals name="OTHER" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CacheType">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="data" literal="DATA"/>
    <eLiterals name="instruction" literal="INSTRUCTION"/>
    <eLiterals name="unified" literal="UNIFIED"/>
    <eLiterals name="other" literal="OTHER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LengthUnit">
    <eLiterals name="_undefined_" literal="&lt;UNDEFINED>"/>
    <eLiterals name="mm" literal="MM"/>
    <eLiterals name="cm" literal="CM"/>
  </eClassifiers>
</ecore:EPackage>
