/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.itea2.amalthea.variability.dependency.ui.AbstractDependencyUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DependencyUiModule extends AbstractDependencyUiModule {
  public DependencyUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
