/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.dependency;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.Dependency#getFlatDependency <em>Flat Dependency</em>}</li>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.Dependency#getHierarchicalDependencies <em>Hierarchical Dependencies</em>}</li>
 * </ul>
 *
 * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Flat Dependency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Flat Dependency</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Flat Dependency</em>' containment reference.
   * @see #setFlatDependency(FlatDependency)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getDependency_FlatDependency()
   * @model containment="true"
   * @generated
   */
  FlatDependency getFlatDependency();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.Dependency#getFlatDependency <em>Flat Dependency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Flat Dependency</em>' containment reference.
   * @see #getFlatDependency()
   * @generated
   */
  void setFlatDependency(FlatDependency value);

  /**
   * Returns the value of the '<em><b>Hierarchical Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link org.itea2.amalthea.variability.dependency.dependency.HierarchicalDependency}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hierarchical Dependencies</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hierarchical Dependencies</em>' containment reference list.
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getDependency_HierarchicalDependencies()
   * @model containment="true"
   * @generated
   */
  EList<HierarchicalDependency> getHierarchicalDependencies();

} // Dependency
