/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.dependency;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flat Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.FlatDependency#getSystemPart <em>System Part</em>}</li>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.FlatDependency#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getFlatDependency()
 * @model
 * @generated
 */
public interface FlatDependency extends EObject
{
  /**
   * Returns the value of the '<em><b>System Part</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System Part</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System Part</em>' containment reference.
   * @see #setSystemPart(SystemPart)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getFlatDependency_SystemPart()
   * @model containment="true"
   * @generated
   */
  SystemPart getSystemPart();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.FlatDependency#getSystemPart <em>System Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>System Part</em>' containment reference.
   * @see #getSystemPart()
   * @generated
   */
  void setSystemPart(SystemPart value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getFlatDependency_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.FlatDependency#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

} // FlatDependency
