/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.dependency;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.Property#getName <em>Name</em>}</li>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.Property#getComparismOperator <em>Comparism Operator</em>}</li>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.Property#getValue <em>Value</em>}</li>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.Property#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.Property#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Comparism Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.itea2.amalthea.variability.dependency.dependency.ComparismOperator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comparism Operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparism Operator</em>' attribute.
   * @see org.itea2.amalthea.variability.dependency.dependency.ComparismOperator
   * @see #setComparismOperator(ComparismOperator)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getProperty_ComparismOperator()
   * @model
   * @generated
   */
  ComparismOperator getComparismOperator();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.Property#getComparismOperator <em>Comparism Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparism Operator</em>' attribute.
   * @see org.itea2.amalthea.variability.dependency.dependency.ComparismOperator
   * @see #getComparismOperator()
   * @generated
   */
  void setComparismOperator(ComparismOperator value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(PropertyValue)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getProperty_Value()
   * @model containment="true"
   * @generated
   */
  PropertyValue getValue();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.Property#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(PropertyValue value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(Description)
   * @see org.itea2.amalthea.variability.dependency.dependency.DependencyPackage#getProperty_Description()
   * @model containment="true"
   * @generated
   */
  Description getDescription();

  /**
   * Sets the value of the '{@link org.itea2.amalthea.variability.dependency.dependency.Property#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(Description value);

} // Property
