/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.dependency.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.itea2.amalthea.variability.dependency.dependency.DependencyPackage;
import org.itea2.amalthea.variability.dependency.dependency.FlatDependency;
import org.itea2.amalthea.variability.dependency.dependency.SystemPart;
import org.itea2.amalthea.variability.dependency.dependency.Type;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Flat Dependency</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.impl.FlatDependencyImpl#getSystemPart <em>System Part</em>}</li>
 *   <li>{@link org.itea2.amalthea.variability.dependency.dependency.impl.FlatDependencyImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FlatDependencyImpl extends MinimalEObjectImpl.Container implements FlatDependency
{
  /**
   * The cached value of the '{@link #getSystemPart() <em>System Part</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSystemPart()
   * @generated
   * @ordered
   */
  protected SystemPart systemPart;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Type type;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FlatDependencyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DependencyPackage.Literals.FLAT_DEPENDENCY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemPart getSystemPart()
  {
    return systemPart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSystemPart(SystemPart newSystemPart, NotificationChain msgs)
  {
    SystemPart oldSystemPart = systemPart;
    systemPart = newSystemPart;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART, oldSystemPart, newSystemPart);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSystemPart(SystemPart newSystemPart)
  {
    if (newSystemPart != systemPart)
    {
      NotificationChain msgs = null;
      if (systemPart != null)
        msgs = ((InternalEObject)systemPart).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART, null, msgs);
      if (newSystemPart != null)
        msgs = ((InternalEObject)newSystemPart).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART, null, msgs);
      msgs = basicSetSystemPart(newSystemPart, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART, newSystemPart, newSystemPart));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetType(Type newType, NotificationChain msgs)
  {
    Type oldType = type;
    type = newType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DependencyPackage.FLAT_DEPENDENCY__TYPE, oldType, newType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(Type newType)
  {
    if (newType != type)
    {
      NotificationChain msgs = null;
      if (type != null)
        msgs = ((InternalEObject)type).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DependencyPackage.FLAT_DEPENDENCY__TYPE, null, msgs);
      if (newType != null)
        msgs = ((InternalEObject)newType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DependencyPackage.FLAT_DEPENDENCY__TYPE, null, msgs);
      msgs = basicSetType(newType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DependencyPackage.FLAT_DEPENDENCY__TYPE, newType, newType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART:
        return basicSetSystemPart(null, msgs);
      case DependencyPackage.FLAT_DEPENDENCY__TYPE:
        return basicSetType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART:
        return getSystemPart();
      case DependencyPackage.FLAT_DEPENDENCY__TYPE:
        return getType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART:
        setSystemPart((SystemPart)newValue);
        return;
      case DependencyPackage.FLAT_DEPENDENCY__TYPE:
        setType((Type)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART:
        setSystemPart((SystemPart)null);
        return;
      case DependencyPackage.FLAT_DEPENDENCY__TYPE:
        setType((Type)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DependencyPackage.FLAT_DEPENDENCY__SYSTEM_PART:
        return systemPart != null;
      case DependencyPackage.FLAT_DEPENDENCY__TYPE:
        return type != null;
    }
    return super.eIsSet(featureID);
  }

} //FlatDependencyImpl
