/*
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.ide


/**
 * Use this class to register ide components.
 */
class DependencyIdeModule extends AbstractDependencyIdeModule {
}
