extern void initCarHeadlightCtrl(void);
extern void handleUserInputs(UserInput data);

typedef enum {
	HIGH_BEAM,
	FOG_LIGHT,
	HIGH_BEAM_ASSISTANT,
	TURN_SIGNAL_RIGHT,
	TURN_SIGNAL_LEFT,
	DIM_LIGHT,
	PARKING_LIGHT,
	DAYTIME_RUNNING_LIGHT_ACTIVE,
	DAYTIME_RUNNING_LIGHT_INACTIVE,
	STATIC_CORNERING_LIGHT,
	HAZARD
}UserInput

#define HIGH_BEAM_ASSISTANT
#define FOG_LIGHT
#define STATIC_CORNERING_LIGHT
#define DAYTIME_RUNNING_LIGHT
