/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.ide;

import org.itea2.amalthea.variability.dependency.ide.AbstractDependencyIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DependencyIdeModule extends AbstractDependencyIdeModule {
}
