/*
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.itea2.amalthea.variability.dependency.ui.internal.DependencyActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DependencyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DependencyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DependencyActivator.getInstance().getInjector(DependencyActivator.ORG_ITEA2_AMALTHEA_VARIABILITY_DEPENDENCY_DEPENDENCY);
	}
	
}
