/**
 * generated by Xtext 2.12.0
 */
package org.itea2.amalthea.variability.dependency;

import org.itea2.amalthea.variability.dependency.DependencyStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DependencyStandaloneSetup extends DependencyStandaloneSetupGenerated {
  public static void doSetup() {
    new DependencyStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
